from typing import Any


def drill(
    slug: str,
    title: str,
    track: str,
    sequence: int,
    difficulty: int,
    duration: int,
    objective: str,
    concept: str,
    mistake: str,
    instructions: list[str],
    visual_kind: str,
    self_checks: list[tuple[str, str]],
    *,
    visual_config: dict[str, Any] | None = None,
) -> dict[str, Any]:
    observe = 3 if duration >= 15 else 2
    review = 3
    practice = duration - observe - review
    return {
        "slug": slug,
        "title": title,
        "track": track,
        "difficulty": difficulty,
        "duration_minutes": duration,
        "objective": objective,
        "concept": concept,
        "common_mistake": mistake,
        "materials": ["Paper", "Pencil or fineliner", "A comfortable drawing surface"],
        "instructions": instructions,
        "timed_phases": [
            {"label": "Observe", "minutes": observe, "instruction": instructions[0]},
            {"label": "Practice", "minutes": practice, "instruction": instructions[1]},
            {"label": "Check", "minutes": review, "instruction": instructions[2]},
        ],
        "visual_kind": visual_kind,
        "visual_config": visual_config
        or {
            "mode": "3d"
            if visual_kind in {"rotating", "draw-through", "cross-contour", "object", "light-logic"}
            else "diagram"
        },
        "variation_config": {"generator": visual_kind, "version": "library_v1"},
        "self_checks": [{"id": check_id, "label": label} for check_id, label in self_checks],
        "sequence_index": sequence,
    }


LIBRARY_EXERCISES: list[dict[str, Any]] = [
    drill(
        "one-point-box-field",
        "One-Point Box Field",
        "perspective",
        1,
        1,
        12,
        "Place solid boxes above and below a shared horizon.",
        "In one-point perspective, the front faces stay flat while every depth edge aims toward one vanishing point.",
        "Tilting front-face verticals or letting depth edges drift toward different destinations.",
        [
            "Locate the horizon and vanishing point before making a box.",
            "Draw four front faces, then send each depth edge toward the same point.",
            "Reveal the guides and extend your depth edges lightly.",
        ],
        "one-point",
        [
            ("shared-vp", "Depth edges aim toward the shared vanishing point."),
            ("upright-fronts", "Front-face verticals remain upright."),
            ("horizon-read", "Top or bottom faces change correctly across the horizon."),
        ],
    ),
    drill(
        "two-point-boxes",
        "Two-Point Boxes",
        "perspective",
        2,
        2,
        15,
        "Construct boxes whose two horizontal edge families converge consistently.",
        "A rotated box sends its left and right edge families toward separate vanishing points on the same horizon.",
        "Making both edge families parallel or allowing individual edges to choose unrelated angles.",
        [
            "Mark the horizon and compare the two convergence directions.",
            "Build three boxes at different heights while keeping their verticals upright.",
            "Reveal both guide families and compare each drawn edge.",
        ],
        "two-point",
        [
            ("two-families", "Each horizontal edge belongs to one of two consistent families."),
            ("verticals", "Vertical edges remain upright."),
            ("eye-level", "Visible top and bottom faces agree with eye level."),
        ],
    ),
    drill(
        "rotating-primitives",
        "Rotating Primitives",
        "perspective",
        3,
        2,
        15,
        "Draw one primitive from three generated viewpoints.",
        "Rotation changes the proportion and direction of visible faces, but the form's internal relationships stay coherent.",
        "Redrawing a memorized symbol instead of responding to which surfaces are visible.",
        [
            "Compare the three views and name what becomes more or less visible.",
            "Draw the primitive three times, preserving its main axis and proportions.",
            "Reveal axes and edge families to inspect the rotation.",
        ],
        "rotating",
        [
            ("view-change", "Each drawing shows a clear change in viewpoint."),
            ("axis", "The primitive's main axis stays internally consistent."),
            ("proportion", "Visible faces change proportion rather than merely sliding sideways."),
        ],
    ),
    drill(
        "draw-through-forms",
        "Draw Through Forms",
        "solid_form",
        4,
        1,
        12,
        "Construct the complete volume before clarifying the visible contour.",
        "Lightly drawing hidden edges prevents a form from becoming a collection of disconnected visible fragments.",
        "Darkening the final contour before the hidden construction agrees.",
        [
            "Identify the complete primitive, including the surfaces facing away from you.",
            "Draw every edge lightly, then strengthen only the visible contour.",
            "Reveal hidden edges and compare the full construction.",
        ],
        "draw-through",
        [
            ("complete-volume", "Hidden and visible edges describe one complete volume."),
            ("light-hidden", "Hidden construction remains lighter than visible contour."),
            ("corners-connect", "Corners and ellipse axes connect consistently."),
        ],
    ),
    drill(
        "cross-contour-wraps",
        "Cross-Contour Wraps",
        "solid_form",
        5,
        2,
        15,
        "Use cross-contours to show how a surface turns away from the viewer.",
        "A cross-contour travels across a surface like a ribbon wrapped around it, changing curvature as the form turns.",
        "Drawing flat stripes that ignore the primitive's axis and silhouette.",
        [
            "Find the primitive's long axis and imagine evenly spaced ribbons.",
            "Wrap six to eight contours around the surface without tracing the outline.",
            "Reveal the reference contours and compare their curvature near the edges.",
        ],
        "cross-contour",
        [
            ("wrap", "Contours visibly wrap around rather than sit flat."),
            ("axis", "Contours remain organized around the form's main axis."),
            ("edge-turn", "Curvature increases as the surface turns toward the silhouette."),
        ],
    ),
    drill(
        "everyday-object-construction",
        "Build an Everyday Object",
        "solid_form",
        6,
        3,
        20,
        "Build a mug, bottle, or stool from connected primitive forms.",
        "Construction drawing starts with simple volumes, aligns their axes, and uses overlap to explain how the parts connect.",
        "Chasing the final silhouette before the underlying primitives share a believable space.",
        [
            "Name the two or three primitives inside the generated object.",
            "Draw through each form, connect them, then clarify the outer contour.",
            "Reveal the primitive scaffold and inspect axes, overlap, and proportion.",
        ],
        "object",
        [
            ("primitive-read", "The object can be understood as a small set of simple forms."),
            ("shared-space", "The forms share a believable orientation and scale."),
            ("overlap", "Overlaps clearly explain which part sits in front."),
        ],
    ),
    drill(
        "five-value-hatch-ladder",
        "Five-Value Hatch Ladder",
        "hatching_light",
        7,
        1,
        12,
        "Create five distinct values by changing hatch spacing, not pressure.",
        "Consistent strokes become darker when they are placed closer together or crossed with an additional direction.",
        "Scribbling, pressing harder, or changing several variables at once.",
        [
            "Study the generated hatch angle and plan five equal boxes.",
            "Fill the ladder from paper white to darkest using controlled spacing.",
            "Reveal the target ladder, squint, and compare separation between steps.",
        ],
        "hatch-ladder",
        [
            ("distinct-values", "All five steps remain distinct when viewed from a distance."),
            ("spacing", "Spacing—not pressure—creates the main value change."),
            ("stroke-family", "Strokes within each layer stay parallel and deliberate."),
        ],
    ),
    drill(
        "hatching-around-form",
        "Hatching Around Form",
        "hatching_light",
        8,
        2,
        15,
        "Make hatching describe both value and surface direction.",
        "Marks can reinforce volume when they curve with the surface and become denser as the form turns away from light.",
        "Using straight, evenly spaced marks across the entire form like a flat sticker.",
        [
            "Locate the light side and imagine contour bands wrapping the primitive.",
            "Hatch with the surface, tightening spacing through the shadow turn.",
            "Reveal the form guides and compare direction and density.",
        ],
        "hatch-form",
        [
            ("surface-direction", "Hatches follow the turning direction of the surface."),
            ("density-turn", "Density increases gradually toward shadow."),
            ("light-preserved", "The lightest area remains open and readable."),
        ],
    ),
    drill(
        "light-logic-primitives",
        "Light Logic on Primitives",
        "hatching_light",
        9,
        3,
        20,
        "Organize light and shadow so a primitive feels convincingly solid.",
        "Form reads through ordered value groups: light, halftone, core shadow, reflected light, and a cast shadow directed away from the source.",
        "Rendering smooth texture before deciding the large light and shadow families.",
        [
            "Locate the generated light and identify the large light-shadow division.",
            "Block the shadow family first, then add controlled halftones and cast shadow.",
            "Reveal the light map and compare the value order and cast-shadow direction.",
        ],
        "light-logic",
        [
            ("family-separation", "The light and shadow families remain clearly separated."),
            ("value-order", "Core shadow stays darker than reflected light."),
            ("cast-direction", "The cast shadow travels away from the light source."),
        ],
    ),
    drill(
        "head-as-form",
        "Head as a Turning Form",
        "portrait_foundations",
        10,
        1,
        15,
        "Construct a believable head from a sphere, side plane, jaw, and center line.",
        "A head is a three-dimensional form. The center line and brow axis wrap around it and make the direction of the face readable before features are added.",
        "Drawing a flat oval, then placing features as symbols without accounting for the turn.",
        [
            "Read the generated head turn and trace the center and brow axes in the air.",
            "Build three heads from sphere, side plane, and jaw before adding any features.",
            "Reveal the construction and compare the tilt, center line, and jaw attachment.",
        ],
        "head-construction",
        [
            ("turn", "The center line clearly describes the direction of the head."),
            ("brow-wrap", "The brow axis wraps around the cranial form."),
            ("jaw-attach", "The jaw connects to the side plane instead of hanging from the oval."),
        ],
    ),
    drill(
        "facial-proportion-map",
        "Facial Proportion Map",
        "portrait_foundations",
        11,
        1,
        15,
        "Place the brow, eyes, nose, mouth, ears, and chin as related landmarks.",
        "Portrait proportions are relationships rather than rigid formulas. A simple landmark map gives you a neutral baseline to observe and adjust for a specific face.",
        "Measuring every feature separately instead of comparing intervals across the whole head.",
        [
            "Identify the brow, eye, nose, mouth, ear, and chin landmarks on the generated map.",
            "Draw four heads and place landmarks by comparing one interval to the next.",
            "Reveal the guide, then note which relationship drifted most consistently.",
        ],
        "facial-proportions",
        [
            (
                "eye-line",
                "The eyes share a coherent axis halfway through the cranial-and-jaw form.",
            ),
            (
                "feature-spacing",
                "Feature intervals feel intentionally related rather than independently guessed.",
            ),
            ("ear-range", "The ears align plausibly with the brow-to-nose region."),
        ],
    ),
    drill(
        "features-around-the-turn",
        "Features Around the Turn",
        "portrait_foundations",
        12,
        2,
        20,
        "Place paired facial features on a head that turns away from the viewer.",
        "Features sit on curved planes. As the head turns, the far side compresses, the center line shifts, and both features continue to share wrapped axes.",
        "Sliding a front-facing feature chart sideways while keeping both sides equally wide.",
        [
            "Study how the far eye and far corner of the mouth compress in the generated turn.",
            "Construct three turned heads, placing sockets, nose wedge, and mouth on shared axes.",
            "Reveal the facial planes and compare near-side width, far-side compression, and center line.",
        ],
        "facial-turn",
        [
            (
                "compression",
                "The far side compresses without disappearing or matching the near side.",
            ),
            ("shared-axes", "Eyes, nose, and mouth agree with the same head turn."),
            (
                "feature-volume",
                "Features attach to facial planes instead of floating on the outline.",
            ),
        ],
    ),
    drill(
        "gesture-action-lines",
        "Gesture: Action and Balance",
        "figure_creature",
        13,
        1,
        12,
        "Capture movement in human and animal poses before drawing anatomy.",
        "A gesture begins with the longest directional rhythm, then places the head, rib cage, pelvis, and weight-bearing limbs around that action.",
        "Tracing the outside contour slowly and losing the pose's balance and energy.",
        [
            "Find the longest action line and the point carrying the subject's weight.",
            "Make six 45-second gestures using only action, masses, and limb rhythms.",
            "Reveal the balance line and compare whether each pose could physically stay upright.",
        ],
        "creature-gesture",
        [
            ("action", "One clear action line carries through the pose."),
            ("weight", "The center of mass relates believably to the supporting limbs."),
            ("simplicity", "Large masses and rhythms read before contour detail."),
        ],
    ),
    drill(
        "human-mannequin",
        "Human Mannequin",
        "figure_creature",
        14,
        2,
        20,
        "Build a human pose from rib cage, pelvis, head, and jointed limb forms.",
        "The figure becomes manageable when the torso is treated as two masses connected by a flexible spine and the limbs are simple tapered cylinders organized around joints.",
        "Building a stiff stick figure or adding muscles before the rib cage and pelvis establish the pose.",
        [
            "Locate the head, rib cage, pelvis, spine rhythm, and supporting leg.",
            "Construct three mannequins with simple joint markers and tapered limb forms.",
            "Reveal the mass-and-joint scaffold and compare tilt, overlap, and balance.",
        ],
        "human-mannequin",
        [
            ("torso-masses", "Rib cage and pelvis read as separate, related volumes."),
            (
                "joint-chain",
                "Limbs bend from clearly placed shoulder, elbow, hip, and knee joints.",
            ),
            ("balance", "The standing figure's weight resolves over its support."),
        ],
    ),
    drill(
        "quadruped-body-masses",
        "Quadruped Body Masses",
        "figure_creature",
        15,
        1,
        15,
        "Construct a dog- or cat-like body from head, chest, pelvis, spine, and limb rhythms.",
        "Most quadrupeds can be organized around two major torso masses joined by a flexible spine, with limbs hanging from the shoulder and hip structures rather than the belly contour.",
        "Drawing a single bean-shaped torso and attaching four identical legs to its underside.",
        [
            "Compare the chest and pelvis masses and identify the spine's direction.",
            "Build four quadrupeds from two torso masses, a head wedge, and simple limb rhythms.",
            "Reveal the scaffold and check where each near and far limb attaches.",
        ],
        "quadruped-masses",
        [
            ("two-masses", "Chest and pelvis remain distinct and connected by the spine."),
            (
                "limb-attach",
                "Forelimbs attach near the shoulder mass and hind limbs near the pelvis.",
            ),
            ("depth-pairs", "Near and far legs are separated through overlap and placement."),
        ],
    ),
    drill(
        "animal-leg-rhythms",
        "Animal Leg Rhythms",
        "figure_creature",
        16,
        2,
        15,
        "Understand the shared joint pattern beneath human, dog, and cat limbs.",
        "Mammal limbs share a related bone plan, but different segment lengths and weight-bearing contact create distinct rhythms. Comparing them prevents backward-knee symbols and tube legs.",
        "Copying the outer silhouette without locating the shoulder or hip, elbow or knee, wrist or ankle, and ground contact.",
        [
            "Follow the generated limb from body attachment through each joint to the ground.",
            "Draw the human, dog, and cat limb rhythms side by side as tapered segments.",
            "Reveal the joint chain and compare segment direction, length, and contact point.",
        ],
        "animal-legs",
        [
            ("joint-order", "The joint chain follows a believable anatomical order."),
            ("taper", "Limb segments taper toward the ground instead of reading as tubes."),
            ("ground-contact", "Feet or paws support weight with a clear contact plane."),
        ],
    ),
    drill(
        "dog-head-planes",
        "Dog Head Planes",
        "figure_creature",
        17,
        2,
        15,
        "Build a canine head from cranial mass, muzzle box, cheek planes, and ear attachments.",
        "A dog's muzzle projects from the cranial mass as a separate volume. Breed variation changes proportions, but the center line, eye axis, and muzzle direction must still agree.",
        "Drawing the muzzle as a flat shape pasted inside the head outline.",
        [
            "Compare the generated muzzle length, ear set, and head turn.",
            "Construct three dog heads from cranium and muzzle volumes before adding nose or eyes.",
            "Reveal the planes and compare muzzle projection, eye axis, and ear attachment.",
        ],
        "dog-head",
        [
            (
                "muzzle-volume",
                "The muzzle projects as a box-like volume with a readable front plane.",
            ),
            ("axis-agreement", "Cranium, eyes, and muzzle share the same turn."),
            ("ear-attach", "Ears attach to the cranial mass rather than the outer silhouette."),
        ],
    ),
    drill(
        "cat-head-construction",
        "Cat Head Construction",
        "figure_creature",
        18,
        2,
        15,
        "Construct a feline head while preserving its short muzzle, wide cheek structure, and mobile ears.",
        "A cat head combines a rounded cranium with a compact muzzle and broad cheek plane. Ear direction and pupil axis help communicate both turn and attention.",
        "Using a generic circular face with triangle ears and no muzzle or cheek structure.",
        [
            "Read the generated head turn, ear direction, and compact muzzle wedge.",
            "Build three cat heads from cranium, cheek plane, muzzle, and ear forms.",
            "Reveal the scaffold and compare cheek width, muzzle placement, and ear perspective.",
        ],
        "cat-head",
        [
            ("cheek-structure", "The cheek width bridges the cranium and compact muzzle."),
            ("ear-perspective", "Both ears attach and turn consistently with the head."),
            ("muzzle-center", "The nose and muzzle remain centered on the wrapped facial axis."),
        ],
    ),
    drill(
        "paws-and-ground-contact",
        "Paws and Ground Contact",
        "figure_creature",
        19,
        2,
        15,
        "Simplify paws into weight-bearing blocks, toe fans, and contact planes.",
        "A paw communicates weight through the wrist or ankle direction, the main pad mass, the spread of toes, and the plane where it meets the ground.",
        "Ending each leg in a small symbol that ignores perspective, spread, and pressure against the floor.",
        [
            "Identify the limb direction, paw block, toe fan, and ground plane.",
            "Draw six paws from the generated front, side, and three-quarter orientations.",
            "Reveal the contact guide and compare tilt, toe spread, and weight compression.",
        ],
        "animal-paws",
        [
            ("paw-block", "The paw reads as a small volume rather than a flat icon."),
            ("toe-fan", "Toes spread from the main pad in perspective."),
            ("contact", "The lowest plane makes convincing contact with the ground."),
        ],
    ),
    drill(
        "invented-creature-synthesis",
        "Invented Creature Synthesis",
        "figure_creature",
        20,
        3,
        20,
        "Design a believable creature by combining studied mammal structures with one intentional variation.",
        "Creature design becomes convincing when invention is anchored to gesture, weight, joint logic, and functional masses. Exaggeration works best when the underlying body could still move.",
        "Combining surface traits while ignoring how the skeleton carries weight or how the limbs articulate.",
        [
            "Choose the generated body plan and identify the locomotion or behavior it must support.",
            "Build the creature from gesture, chest, pelvis, head, and jointed limbs before adding one species-inspired variation.",
            "Reveal the functional scaffold and check balance, limb logic, and clarity of the chosen adaptation.",
        ],
        "creature-synthesis",
        [
            ("function", "The body plan visibly supports the creature's intended movement."),
            ("anatomy-logic", "Major masses and joints connect in a believable way."),
            (
                "clear-variation",
                "One intentional adaptation is clear without obscuring the construction.",
            ),
        ],
    ),
]
